#!/usr/bin/env bash

set -e

DIR="$(pwd)"

# Order of docker-compose yaml files
#
# 1) docker-compose.yaml
# 2) docker-compose-override.yaml

source "$DIR/.flaskenv"

ENV_OVERRIDE_FILE="$DIR/.flaskenv.override"
if [ -f $ENV_OVERRIDE_FILE ]; then
  source $ENV_OVERRIDE_FILE;
fi

ARGS=(-f "$DIR/docker-compose.yml")

COMPOSE_OVERRIDE_FILE="$DIR/docker-compose-override.yml"

if [ -f "$COMPOSE_OVERRIDE_FILE" ]; then
    ARGS+=(-f "$COMPOSE_OVERRIDE_FILE")
fi

docker-compose "${ARGS[@]}" "$@"
