#!/usr/bin/env bash

set -e

DIR="$(pwd)"

source "$DIR/.flaskenv"

ENV_OVERRIDE_FILE="$DIR/.flaskenv.override"
if [ -f $ENV_OVERRIDE_FILE ]; then
  source $ENV_OVERRIDE_FILE;
fi

flask_container() {
    ARGS=()

    if [ ! -t 0 ]; then
        ARGS+=(-T)
    fi

    ARGS+=(--user "$(id -u)")

    if ! docker/compose ps | grep "_flask_" | grep "Up" &> /dev/null; then
        docker/compose run --rm --no-deps -p "$PORT:$PORT" "${ARGS[@]}" web "$@"

        return
    fi

    docker/compose exec "${ARGS[@]}" node "$@";
}

flask_container "$@"
